<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NISANTH" failures="1" tests="1" name="Chrome Test" time="26.801" errors="0" timestamp="2023-03-28T21:43:34 IST">
  <testcase classname="com.trello.qsipders.learntestng.SoftAssertAutomationScript" name="checkLogOut" time="13.719">
    <failure type="java.lang.AssertionError" message="The script fail due to
	expected [https:/demo.actitime.com/login.do] but found [https://demo.actitime.com/login.do]">
      <![CDATA[java.lang.AssertionError: The script fail due to
expected [https:/demo.actitime.com/login.do] but found [https://demo.actitime.com/login.do]
at com.trello.qsipders.learntestng.SoftAssertAutomationScript.checkLogOut(SoftAssertAutomationScript.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkLogOut -->
</testsuite> <!-- Chrome Test -->
