<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NISANTH" failures="1" tests="1" name="hardassertTest" time="29.551" errors="0" timestamp="2023-03-28T21:48:18 IST">
  <testcase classname="com.trello.qsipders.learntestng.HardAssertAutomationScript" name="checkLogOut" time="15.864">
    <failure type="java.lang.AssertionError" message="The script problem in
	expected [https:/demo.actitime.com/login.do] but found [https://demo.actitime.com/login.do]">
      <![CDATA[java.lang.AssertionError: The script problem in
expected [https:/demo.actitime.com/login.do] but found [https://demo.actitime.com/login.do]
at com.trello.qsipders.learntestng.HardAssertAutomationScript.checkLogOut(HardAssertAutomationScript.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- checkLogOut -->
</testsuite> <!-- hardassertTest -->
